### ISSUE TITLE
 requests==2.22.0 too strict

### ISSUE THREAD

**Issue by runningman84** [timvancann/pyavri#1]
Please allow higher versions of the requests library:
ERROR: avri-api 0.1.7 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.

**Comment by MartinHjelmare** [comment]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by timvancann** [comment]
Issue resolved!
