### ISSUE TITLE
Please file releases...

### ISSUE THREAD

**Issue by onkelbeh** [timvancann/pyavri#2]
Hi Tim,

I would like to include your component in [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository), hope you don't mind.

Therefore I need source files in Pypi's SDIST format, or Github archives.
On Pypi you have only files in Wheel format, which I cannot use
and: you do not file releases on Github, this would be easy.

Please add the tags, at least for the current version (0.1.7).

If you need help, please let me know.

To fix this for now, I forked it and created the release: https://github.com/onkelbeh/pyavri/releases/tag/0.1.7
Added a tick to remember: https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/180
Added the fork to the repo (for completeness): https://github.com/onkelbeh/HomeAssistantRepository/commit/9113071dbbdb8be1a8ebe80cfff1290ada1c654b
won't be really useable at all due to: https://github.com/timvancann/pyavri/issues/1

\B.

**Comment by timvancann** [comment]
I just released a new version of the API to support the new Avri API (they changed in the beginning of december). Also made a tag for it so feel free to use that one!

Also: feel free to use this code in any way you want. I'm happy someone finds it useful :).

**Comment by onkelbeh** [comment]
HA still uses 0.1.7.
Just went through my old tickets to clean up.

**Comment by onkelbeh** [comment]
[Changed the Ebuild to use a direct commit](https://github.com/onkelbeh/HomeAssistantRepository/commit/26483bf5cd71a02a45dee0e02b3a06ceb33d872f), so I could get rid of the fork and the ticket.

**Comment by onkelbeh** [comment]
Unfortunately it was removed from Home Assistant (due to malfunction) in the meantime.
https://github.com/home-assistant/core/issues/43998

I'll add it back to my Repo once it is back integrated.
